apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: flink-demo
  region: us-west-2
managedNodeGroups:
  - name: managed-ng-od
    minSize: 1
    maxSize: 10
    desiredCapacity: 1
    instanceSelector:
      vCPUs: 4
      memory: "8"
      cpuArchitecture: x86_64
    iam:
      attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy   
      - <<Policy ARN>>
      withAddonPolicies:
        autoScaler: true
  - name: managed-ng-spot
    minSize: 1
    maxSize: 20
    desiredCapacity: 1
    instanceSelector:
      vCPUs: 4
      memory: "8" 
      cpuArchitecture: x86_64
    spot: True
    iam:
      attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      - <<Policy ARN>>
      withAddonPolicies:
        autoScaler: true